name: drowsy
description: Application for detecting drowsniess

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^2.0.0
  font_awesome_flutter: ^8.0.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  shared_preferences: ^0.5.12+4

  image: ^2.1.19
  camera: ^0.5.8+7

  firebase_ml_vision: ^0.9.10
  path_provider: ^1.6.27
  audioplayers: ^0.17.0
  geolocator: ^6.1.13
  flutter_sms: ^2.1.1
  twilio_flutter: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

